package:
  name: ipart
  version: 3.0.6

source:
  url: https://github.com/ihesp/IPART/archive/v3.0.6.tar.gz
  sha256: c9c145bd144ccbf1ff0b839cfbc41a5e85bcd68b38e426de5bf8786c5b440c1f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - netcdf4
    - scikit-image
    - networkx
    - matplotlib

test:
  imports:
    - ipart
    - ipart.utils
  source_files:
    - tests
  commands:
    - python -m unittest discover -s tests

about:
  home: https://github.com/ihesp/IPART
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: 'IPART is a Python package for the detection and tracking of atmospheric rivers from gridded IVT data using image-processing techniques'
  description: |
    IPART is a Python package for the detection and tracking of atmospheric
    rivers from gridded (Integrated Vapor Transport) IVT data using image-processing techniques
  doc_url: https://ipart.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - Xunius
